### ISSUE TITLE
delete test dynamodb tables after tests

### ISSUE THREAD

**Issue by etoccalino** [etoccalino/aws-test-utils#6]
New support for DynamoDB does not seem to be deleting the tables used during the tests. This incurs in unnecessary AWS costs.

**Comment by hariom12** [comment]
If you are using AWS account and creating table you have the option to delete.

**Comment by etoccalino** [comment]
You're right @hariom12. In fact, I just noticed that @fnmartinez  did add appropriate code at the context manager `__exit__()` for the table deletion to happen automatically. I'll have to further test to confirm the issue.
